apiVersion: v1
kind: Pod 
metadata: 
  name: test
spec: 
  containers: 
    -  image: nginx
       name: c1
    -  image: busybox
       name: c2
       command: 
         -  sleep
         -  "3600"
    - image: postgres
      name: c3
